### ISSUE TITLE
Please add split arrow Icon

### ISSUE THREAD

**Issue by alanmynah** [HT2-Labs/mural#195]
I've spoken to Sophia and she said that I cannot have this Icon. Is there a way to get it? 

https://material.io/tools/icons/?icon=call_split&style=baseline

**Comment by GooBall** [comment]
@alanmynah You need to find it in fontawesome and then @Sophie009 knows what to do to add it in here :wink:

**Comment by Sophie009** [comment]
@GooBall I couldn't find it in fontawesome. I'll search again. Maybe something with the names.

**Comment by Sophie009** [comment]
@GooBall @alanmynah  The only "similar" icon I could find is that: https://fontawesome.com/icons/code-branch?style=solid
Otherwise we have to decide a different one.

**Comment by alanmynah** [comment]
@ee0pdt, can the icon Sophia is suggesting replace the icon you had in mind? The modal in question is `UserGoalCompleteAll.tsx`
![image](https://user-images.githubusercontent.com/26703675/46944531-2f17cd80-d06a-11e8-9ab7-1c0d15bf0504.png)

**Comment by ee0pdt** [comment]
Any reason we wouldn't just use the Pencil icon? It's really an Edit function in disguise

**Comment by ee0pdt** [comment]
@Sophie009 @alanmynah ^

**Comment by alanmynah** [comment]
The only reason i can think of is your initial design with a split arrow for change journey.

**Comment by Sophie009** [comment]
@ee0pdt Ok I'll add the edit button and if you are ok we can close this issue.
