### ISSUE TITLE
Suggestion: Add useful info to the Icons as prefixes

### ISSUE THREAD

**Issue by ee0pdt** [HT2-Labs/mural#227]
Where we pull icons from existing libraries it might be useful to identify the library by some prefix. Likewise we could identify our own designs in the same way.

e.g.

```
IconFaPencil
IconMuiCalendar
IconHt2Curatr
```

This would help if:

1. Another HT2 product starts using Mural and there's an argument over which design language to use, Or

2. FA doesn't have a particular icon and we chose one from MUI and then FA adds it in the future but LL wants to stick with the FA one

3. We like to use the standard FA pencil icon in the _admin_ but on the _frontend_ we decide to use a friendly HT2 design instead.

4. We decide to change an icon design and want to A/B test them

Or hey, just to let us acknowledge where things were sourced from.

**Comment by wobrien** [comment]
Archiving repository
